version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "installing something"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - grep -Fq "submitToAPIFlatten" Index.html
            - grep -Fq "submitToAPINest" Index.html
            - grep -Fq "submitToAPIReset" Index.html
            - grep -Fq "ls.flatten" Json-Flatten-Nest-CFN.yml
            - grep -Fq "ls.unflatten" Json-Flatten-Nest-CFN.yml
    post_build:
        commands:
            - echo "we are in the post build phase"
artifacts:
  files:
    - 'Index.html'
    - 'error.html'	
  name: flatten-nest-json-cicd-artifacts	            
