AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with cfn-response.
Resources:
  primer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.8
      Role: arn:aws:iam::249660410482:role/service-role/Json-Flatten-Nest-role-4oenas5e
      Handler: flatten_nest_json.handler
      Code:
        ZipFile: |
          import json
          import flatten_json as ls

          def flatten_nest_json(event, context):

    
              #fetch the event body that has the input json coming from the website
    
              json_body = event['body']
              print('abc')
              #Converts string to Json python dictionary
              json_body1 = json.loads(json_body)
    
              #invoke the flatten built in function.
              if event['requestContext'] ['stage' ] == 'Flatten' :
                  output_json = ls.flatten(json_body1,".")
        
              if event['requestContext'] ['stage' ] == 'Nest' :
                  output_json = ls.unflatten(json_body1,".")

              response = {
                  'isBase64Encoded': False,
                  'statusCode': 200, 
                  'headers': { 
                      'Access-Control-Allow-Origin': '*',
                      'Access-Control-Allow-Methods': 'POST, OPTIONS',
                      'Access-Control-Allow-Headers': 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'
                  },
                  'body': json.dumps(output_json)  
                  }
              return response 
      Description: Invoke a function during stack creation.
      Layers:
          - arn:aws:lambda:us-east-1:249660410482:layer:flattennestjson1:1
      TracingConfig:
        Mode: Active